### ISSUE TITLE
Solution for Weather Showing in F or C

### ISSUE THREAD

**Issue by JonasNapierski** [SolDoesTech/HyprV4#10]
I have adjusted the script so that you can now set whether the temperature is Fahrenheit or Celsius. I would develop further so that by a command line flag the temperature format changes, but I had no time for that yet. 
 
[**My Version**](https://github.com/JonasNapierski/Hyprv3/blob/main/waybar/scripts/waybar-wttr.py)

## Todos 
- [ ] add flag for fahrheit
- [ ] add flag for celcius
- [ ] create guide on how to use the new system.

With kind regards
- Jonas
